drop view ferdatum cascade constraints;
drop view ferbuchung cascade constraints;
drop view ferfertig cascade constraints;
drop view top cascade constraints;
drop table Ferienwohnung cascade constraints;
drop table bietet cascade constraints;
drop table beinhaltet cascade constraints;
drop table Adresse cascade constraints;
drop table Bilder cascade constraints;
drop table Land cascade constraints;
drop table Ausstattung cascade constraints;
drop table Touristenattraktion cascade constraints;
drop table Buchung cascade constraints;
drop table Kunde cascade constraints;
drop table Auszahlung cascade constraints;
purge recyclebin;
